Modulo de Segurança
gonLeo/poligym pull request #33
Opened 2021-01-25 18:57 UTC by PedroZenere

Neste modulo foi implementado a parte de login e autenticação JWT. Para que funcione corretamente, primeiramente deverá ser criado um usuário no banco. Seguindo uma recomendação todas as rotas a partir de agora terão /v1/... antes de tudo, exemplo: "baseUrl/v1/users". Para criação do usuário pode-se criar sendo admin ou user. Temos 2 tipos de perfis executando, sendo que somente o user admin poderá excluir algo do banco. Quando criar o usuário, é necessario realizar o login passando o email e a senha pela rota: baseUrl/login, após ter sucesso, no header estará setado o token do usuário, para executar as demais requisições, basta copiar o token e colocar no Header da requisição no formato: Authorization Bearer **token**

2021-01-26 11:55 UTC, matheusjcn requested changes

2021-01-26 11:55 UTC, matheusjcn commented on src/main/java/com/poligym/controller/MuscularGroupController.java
> +  @GetMapping(path = "/users/muscular-groups/{id}")
Nessa função não é necessário o /{id}, pois como implementamos o soft-delete, ela retorna todos os "muscular-groups", que não foram excluídos;

2021-01-26 11:55 UTC, matheusjcn commented on src/main/java/com/poligym/controller/MuscularGroupController.java
> +  @GetMapping(path = "/users/muscular-group")
E aqui temos que passar o "/all" pra diferenciar da outra chamada.

2021-01-28 20:14 UTC, gonLeo commented on src/main/java/com/poligym/models/Users.java
> +    @Column(name = "email", nullable = false, unique = true)
Boa!

2021-01-28 20:16 UTC, gonLeo approved these changes

2021-02-01 03:10 UTC, merged